"""Revision_2

Revision ID: 8e19852bf745
Revises: 35afc883d346
Create Date: 2023-10-28 00:51:52.612841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e19852bf745'
down_revision = '35afc883d346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
